on:
  push:
    paths:
      - '.github/workflows/test.yml'
  workflow_dispatch:
  
name: test
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          id
          groups
          cat /etc/group
          cat /etc/passwd
  test2:
    runs-on: ubuntu-latest
    container: joscherrer/actions-images:makedeb
    steps:
      - name: test
        run: |
          id
          groups
          cat /etc/group
          cat /etc/passwd
          ls -lRah /__w
