on:
  push:
    paths:
      - '.github/workflows/test.yml'
  workflow_dispatch:
  
name: test
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          id
          groups
          cat /etc/group
          cat /etc/passwd
          echo "${{ github.workspace }}"
  test2:
    runs-on: ubuntu-latest
    container: joscherrer/actions-images:makedeb
    steps:
      - name: Set permissions
        run: |
          env
          echo "${{ github.workspace }}"
          groups
          ls -lah /
          ls -lah /__w
          # sudo groupadd -g $(stat -c "%g" /__w) docker
          # sudo usermod -aG docker $(whoami)
          # chmod -R g=u /__w
      - name: Test permissions
        run: |
          groups
          ls -lah /
          ls -lah /__w
          touch /__w/test_file_permissions
